added functionality to delete avatar and delete contact
solomiia-sahala/CoKeeper pull request #54
Opened 2021-08-24 11:38 UTC by solomiia-sahala

added functionality to delete avatar and delete contact

2021-08-27 11:19 UTC, alexandrbig requested changes

2021-08-27 11:19 UTC, alexandrbig commented on src/components/EditContact.tsx
> +            window.location.reload();
why do we need to reload the page?

2021-08-30 08:31 UTC, solomiia-sahala commented on src/components/EditContact.tsx
> +            window.location.reload();
we do reload to make api call to get user data from the firebase store with deleted avatar, but there is more simple way just to update the image state of the user. Thank you=)

2021-08-30 17:02 UTC, alexandrbig approved these changes

2021-08-31 07:43 UTC, merged